version: '3.8'

services:
  # PostgreSQL Database for local development
  postgres:
    image: postgres:15-alpine
    container_name: hyper-dyper-postgres
    environment:
      POSTGRES_DB: hyper_dyper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Add healthcheck to ensure DB is ready before connecting
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
